### ISSUE TITLE
Random suggestions

### ISSUE THREAD

**Issue by superfluke** [superfluke/treetweaker#1]
test bigger trunks
dim whitelist
server side only

**Comment by angelnc1989** [comment]
I got a suggestion as well.
Generate saplings for the trees either based on the trunk and leaf material used or defined in a config.

**Comment by NillerMedDild** [comment]
A dimension whitelist would be greatly appreciated :)

**Comment by Sunconure11** [comment]
What about tree shapes based on BoP trees? Also, a tree shape based on mushrooms.

**Comment by Bulldog83** [comment]
One more. How about custom tree shape?

**Comment by superfluke** [comment]
Yeah I'm not against some custom tree shapes, but it's not something I'm planning on coding in the near future. If someone else wants to code a new tree or you know of a modded tree that would be ok with having their tree added in, I'm all for it.

**Comment by angelnc1989** [comment]
Maybe those suggestions should be split into several issues for better visibility.

**Comment by superfluke** [comment]
good point.
