### ISSUE TITLE
trees aren't generating

### ISSUE THREAD

**Issue by TheIsot** [superfluke/treetweaker#12]
I think script is true.And where do I put the file?.I tried to put .zs file on crafttweaker scripts file and acronym treetweaker file but both aren't worked.
Script
```
#loader preinit
import mods.treetweaker.TreeFactory;

var nostalgia = TreeFactory.createTree("nostalgia");
nostalgia.setTreeType("OAK");
nostalgia.setGenBiome("biomesoplenty:origin_island")
nostalgia.setLog("biomesoplenty:leaves_2:8");
nostalgia.setLeaf("minecraft:log");
nostalgia.setBaseBlock("biomesoplenty:grass:5")
nostalgia.setMinHeight(5);
nostalgia.setExtraHeight(3);
nostalgia.setGenFrequency(5);
nostalgia.register();
```

**Comment by superfluke** [comment]
Can you post your crafttweaker log and your latest.log

**Comment by TheIsot** [comment]
[Download](https://download1638.mediafire.com/4cc3i31f8trg/i69pwo97z4p2ha5/log.rar)

**Comment by superfluke** [comment]
You have an error in your script, it should have show this in chat when you loaded the game. 
`Error parsing treetweaker.zs:7 -- ; expected`
The setGeBiome line is missing a semicolon at the end

**Comment by TheIsot** [comment]
oh,thanks dude
