### ISSUE TITLE
Is this mod suffering from any issues regarding scripts themselves?

### ISSUE THREAD

**Issue by Sunconure11** [superfluke/treetweaker#2]
https://pastebin.com/pfJdCrG4

I feel like this script may be broken, since I keep getting various errors from crafttweaker thrown at me after it's making.

**Comment by Sunconure11** [comment]
https://pastebin.com/xhN0XyF7 Crafttweaker log

**Comment by superfluke** [comment]
I think you're just missing `import mods.treetweaker.TreeFactory;` at the top of the script.

**Comment by Sunconure11** [comment]
That seems to have worked.
