### ISSUE TITLE
Trees not spawning on Netherrack.

### ISSUE THREAD

**Issue by ZeroLevels** [superfluke/treetweaker#3]
I've got a few trees to spawn in the Nether, but they won't use netherrack as the base block.  I've spawned them on the upper bedrock layer as well as on magma blocks, but they just don't seem to take to the netherrack itself.  I tried turning off any of the mods I may have that alter the Nether, but that didn't change anything.

**Comment by superfluke** [comment]
I surprised you get anything at all spawning in the nether. Are you seeing trees spawning on bedrock/magma with just treetweaker alone or only with other mods?

**Comment by ZeroLevels** [comment]
Yeah.  Literally with just Crafttweaker, TreeTweaker and nothing else installed, it seems fine.  Just need to target biome **"minecraft:Hell"** and whitelist dimension **-1**.

I didn't know it wasn't expected to be used in only dimensions other than the nether? o.O

**Comment by superfluke** [comment]
Wow totally forgot to set the target biome in my tests. Glad someone around here knows how to use this mod :P I've added some stuff to better pick blocks in the nether so you can have nether trees next update. 
![image](https://user-images.githubusercontent.com/20022336/43282138-55e8112a-90e3-11e8-8b9b-d805c9c40882.png)

**Comment by ZeroLevels** [comment]
Sweet, thanks man! :)
