### ISSUE TITLE
Saplings for custom trees 

### ISSUE THREAD

**Issue by superfluke** [superfluke/treetweaker#4]
![image](https://user-images.githubusercontent.com/20022336/43336102-6dba1abc-919e-11e8-9c46-3d366f301d9c.png)

**Comment by Sunconure11** [comment]
Adding onto this, would it be possible to allow for say, four saplings of the desired tree or whatever to make a mega variant, just like how some vanilla trees work?

**Comment by superfluke** [comment]
Probably not

**Comment by NillerMedDild** [comment]
Any update on this feature? :)

**Comment by superfluke** [comment]
Been a while since I've played around with things. I'll take a look and see if I can get the sapling system going.

**Comment by superfluke** [comment]
Added in version 1.6

**Comment by NillerMedDild** [comment]
That is freaking awesome man, thank you!
