### ISSUE TITLE
Wiki Inconsistencies

### ISSUE THREAD

**Issue by NillerMedDild** [superfluke/treetweaker#7]
Hey!

According to the list of available methods, `spawnBiome` and `dimensionWhitelist` are available, but in the examples they're called `setGenBiome` and `setDimWhitelist`. The examples are correct.

Thank you for a great mod :)

**Comment by superfluke** [comment]
Should be a bit more clear now with the various functions listed like they would actually be used. Glad you're enjoying it :D
